version: '3.7'

services:
  socket-api:
    build:
      context: .
      target: development
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - 9227:9227
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - socket-network
    depends_on:
      - socket-redis
      - socket-postgres
  socket-redis:
    image: redis:5
    networks:
      - socket-network
  socket-postgres:
    container_name: socket-postgres
    image: postgres:12
    restart: always
    networks:
      - socket-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - socket-pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - socket-network
    ports:
      - 8080:8080
networks:
  socket-network:
volumes:
  socket-pgdata:
