version: '3.7'

services:
  socket-api:
    build:
      context: .
      target: development
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
      - 9228:9228
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - socket-network
    depends_on:
      - socket-redis
  socket-redis:
    image: redis:5
    networks:
      - socket-network
networks:
  socket-network:
volumes:
  socket-pgdata:
