// REDIS EVENTS
export const REDIS_SOCKET_EVENT_SEND = 'REDIS_SOCKET_EVENT_SEND';
export const REDIS_SOCKET_EVENT_EMIT_ALL =
  'REDIS_SOCKET_EVENT_EMIT_ALL';
export const REDIS_SOCKET_EVENT_EMIT_AUTHENTICATED =
  'REDIS_SOCKET_EVENT_EMIT_AUTHENTICATED';
